// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your-Web-API-Key-Here',
    appId: '1:390218023467:web:379cfea791d95c7349206e',
    messagingSenderId: '390218023467',
    projectId: 'mangxahoidulich-46e6f',
    authDomain: 'mangxahoidulich-46e6f.firebaseapp.com',
    storageBucket: 'mangxahoidulich-46e6f.firebasestorage.app',
    measurementId: 'G-DSWEB3CKK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'Your-Web-API-Key-Here',
    appId: '1:390218023467:android:90871ee36ec47bf649206e',
    messagingSenderId: '390218023467',
    projectId: 'mangxahoidulich-46e6f',
    storageBucket: 'mangxahoidulich-46e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Your-Web-API-Key-Here',
    appId: '1:390218023467:ios:b17b6a55d61452e649206e',
    messagingSenderId: '390218023467',
    projectId: 'mangxahoidulich-46e6f',
    storageBucket: 'mangxahoidulich-46e6f.firebasestorage.app',
    androidClientId:
        '390218023467-48a3kn0i2l0efm41egt17bkgooidn5t7.apps.googleusercontent.com',
    iosClientId:
        '390218023467-csshshspd6k3o2jtsgl97837n76j3irj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangXaHoiDuLich',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'Your-Web-API-Key-Here',
    appId: '1:390218023467:ios:b17b6a55d61452e649206e',
    messagingSenderId: '390218023467',
    projectId: 'mangxahoidulich-46e6f',
    storageBucket: 'mangxahoidulich-46e6f.firebasestorage.app',
    androidClientId:
        '390218023467-48a3kn0i2l0efm41egt17bkgooidn5t7.apps.googleusercontent.com',
    iosClientId:
        '390218023467-csshshspd6k3o2jtsgl97837n76j3irj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mangXaHoiDuLich',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'Your-Web-API-Key-Here',
    appId: '1:390218023467:web:305e7f05f135aff149206e',
    messagingSenderId: '390218023467',
    projectId: 'mangxahoidulich-46e6f',
    authDomain: 'mangxahoidulich-46e6f.firebaseapp.com',
    storageBucket: 'mangxahoidulich-46e6f.firebasestorage.app',
    measurementId: 'G-4HEM5VXJ54',
  );
}
